#!/usr/bin/env node
// Splits the master .env into one file per container, so each service only receives the variables it reads
// (docker-compose.yml env_file). Zero dependencies; deploy/setup-vps.sh and deploy/update.sh run it.
//
//   node scripts/split-env.mjs                    .env → .env.dashboard, .env.bot, .env.worker (chmod 600)
//   node scripts/split-env.mjs --in path/.env     another master file (outputs go next to it)
//   node scripts/split-env.mjs --check            only report what would change (exit 1 if a file is stale)
//
//   .env.dashboard  NEXT_PUBLIC_SUPABASE_URL/ANON_KEY, HQ_WORKER_URL, HQ_INTERNAL_SECRET, DASHBOARD_URL, AGENTS_DIR
//                   (never the service-role key or the vault key)
//   .env.bot        SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, TELEGRAM_*, DASHBOARD_URL, MONTHLY_BUDGET_USD, BOT_POLL_MS, TZ
//   .env.worker     everything the worker reads, plus names the schema doesn't know (per-client platform tokens
//                   such as SHOPIFY_TOKEN_<SLUG>); never Telegram or [ops] (SUPABASE_DB_URL stays in the master .env)
//   .env.hermes-<agent>  only for agents with HERMES_KEY_<AGENT> + HQ_MCP_TOKEN_<AGENT> set (deploy/hermes): API_SERVER_KEY,
//                   HQ_MCP_TOKEN, HERMES_MODEL, the model provider key(s), TZ. Nothing else.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { FORBIDDEN_IN, HERMES_AGENTS, SERVICE_FILES, belongsTo, parseEnv } from './env-schema.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2).filter((a) => a !== '--');
const opt = (n) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : undefined; };
const IN = path.resolve(opt('--in') ?? path.join(ROOT, '.env'));
const CHECK = args.includes('--check');

/** Writes KEY=VALUE so that parseEnv (and docker compose) read back exactly the same value. */
function line(k, v) {
  if (/^[^\s#'"\\$]*$/.test(v)) return `${k}=${v}`;
  if (!v.includes("'")) return `${k}='${v}'`; // single quotes: literal, no interpolation
  return `${k}="${v.replace(/(["\\$])/g, '\\$1')}"`;
}

/** { service: text } for a parsed master env. Exported for tests. */
export function splitEnv(env) {
  const out = {};
  for (const svc of Object.keys(SERVICE_FILES)) {
    const keys = [...env.keys()].filter((k) => !k.startsWith('__') && belongsTo(k, svc) && !(FORBIDDEN_IN[svc] ?? []).includes(k));
    out[svc] = [`# Generated by scripts/split-env.mjs from the master .env for the ${svc} container. Do not edit: edit .env and re-run.`,
      ...keys.map((k) => line(k, env.get(k)))].join('\n') + '\n';
  }
  return out;
}

/**
 * { '.env.hermes-<agent>': text } for every agent with HERMES_KEY_<AGENT> and HQ_MCP_TOKEN_<AGENT> set (deploy/hermes).
 * Each Hermes container gets ONLY: its API server key, its HQ MCP token, the model id + provider, the model provider key(s), TZ.
 * Never Supabase, vault, RizeHub, platform or other agents' values. Exported for tests.
 */
export function splitHermesEnv(env) {
  const out = {};
  const get = (k) => (env.get(k) ?? '').trim();
  for (const [agent, s] of Object.entries(HERMES_AGENTS)) {
    if (!get(`HERMES_KEY_${s}`) || !get(`HQ_MCP_TOKEN_${s}`)) continue;
    const vars = [
      ['API_SERVER_KEY', get(`HERMES_KEY_${s}`)], ['HQ_MCP_TOKEN', get(`HQ_MCP_TOKEN_${s}`)],
      ['HERMES_MODEL', get(`HERMES_MODEL_${s}`) || get('HERMES_MODEL')], ['HERMES_PROVIDER', get('HERMES_PROVIDER')],
      ['OPENROUTER_API_KEY', get('OPENROUTER_API_KEY')], ['ANTHROPIC_API_KEY', get('ANTHROPIC_API_KEY')],
      ['OPENAI_API_KEY', get('OPENAI_API_KEY')], ['TZ', get('TZ')],
    ].filter(([, v]) => v);
    out[`.env.hermes-${agent}`] = [`# Generated by scripts/split-env.mjs from the master .env for the hermes-${agent} container. Do not edit: edit .env and re-run.`,
      ...vars.map(([k, v]) => line(k, v))].join('\n') + '\n';
  }
  return out;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (!fs.existsSync(IN)) { console.error(`✗ ${IN} not found (cp .env.example .env and fill it in first)`); process.exit(1); }
  const env = parseEnv(fs.readFileSync(IN, 'utf8'));
  const bad = [...env.keys()].filter((k) => k.startsWith('__bad_line_'));
  if (bad.length) { console.error(`✗ ${path.basename(IN)} has lines that are not KEY=VALUE (${bad.map((b) => b.slice(11)).join(', ')}); fix them first (pnpm check:env)`); process.exit(1); }
  const parts = splitEnv(env);
  const files = [...Object.entries(parts).map(([svc, text]) => [SERVICE_FILES[svc], text]), ...Object.entries(splitHermesEnv(env))];
  let stale = 0;
  for (const [name, text] of files) {
    const file = path.join(path.dirname(IN), name);
    const cur = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    const n = text.split('\n').filter((l) => l && !l.startsWith('#')).length;
    if (cur === text) { console.log(`  ✓ ${name} up to date (${n} variables)`); continue; }
    stale++;
    if (CHECK) { console.log(`  ! ${name} ${cur === null ? 'missing' : 'out of date'}`); continue; }
    fs.writeFileSync(file, text, { mode: 0o600 });
    fs.chmodSync(file, 0o600);
    console.log(`  ✓ wrote ${name} (${n} variables, mode 600)`);
  }
  process.exit(CHECK && stale ? 1 : 0);
}
